name: Neo4j.Almaren
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-22.04
    services:
      neo4j:
        image: neo4j:3.5
        ports:
          - 7474:7474
          - 7687:7687
        env:
          neo4j-user: neo4j
          neo4j-password: neo4j
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Update NEO4j password
        run: |
          curl -H "Content-Type: application/json" -XPOST -d '{"password":"neo4j1234"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password
      - name : Check out repository code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Build and test scala version
        run: |
          PGPASSWORD="postgres" psql -c 'create database almaren;' -U postgres -h localhost 
          PGPASSWORD="postgres" psql -c "ALTER USER postgres PASSWORD 'postgres' ;" -U postgres -h localhost 
          PGPASSWORD="postgres" psql -c 'create role runner;' -U postgres -h localhost
          PGPASSWORD="postgres" psql -c 'ALTER ROLE "runner" WITH  LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;' -U postgres -h localhost
          sbt ++2.12.10 test
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
